_target_: rsl_depth_completion.models.benchmarking.adapters.kbnet_module.KBnetLitModule

outlier_removal:
  _target_: kbnet.net_utils.OutlierRemoval
  kernel_size: 7
  threshold: 1.5

transforms:
  train:
    _target_: kbnet.transforms.Transforms
    normalized_image_range:
    - 0
    - 1
    random_flip_type:
    - none
    random_noise_spread: -1
    random_noise_type: none
    random_remove_points:
    - 0.6
    - 0.7
  val:
    _target_: kbnet.transforms.Transforms
    normalized_image_range:
    - 0
    - 1
    

depth_net:
  _target_: kbnet.kbnet_model.KBNetModel
  activation_func: leaky_relu
  deconv_type: up
  # device: cuda
  # device: cpu
  input_channels_depth: 2
  input_channels_image: 3
  max_pool_sizes_sparse_to_dense_pool:
    - 15
    - 17
  max_predict_depth: 100.0
  min_pool_sizes_sparse_to_dense_pool:
    - 5
    - 7
    - 9
    - 11
    - 13
  min_predict_depth: 1.5
  n_convolution_sparse_to_dense_pool: 3
  n_filter_sparse_to_dense_pool: 8
  n_filters_decoder:
    - 256
    - 128
    - 128
    - 64
    - 12
  n_filters_encoder_depth:
    - 16
    - 32
    - 64
    - 128
    - 128
  n_filters_encoder_image:
    - 48
    - 96
    - 192
    - 384
    - 384
  resolutions_backprojection:
    - 0
    - 1
    - 2
    - 3
  weight_initializer: xavier_normal

pose_net:
  _target_: kbnet.posenet_model.PoseNetModel
  encoder_type: "resnet18"
  rotation_parameterization: "axis"
  weight_initializer: "xavier_normal"
  activation_func: "relu"

config:
  # depth_model_restore_path: /media/master/wext/msc_studies/second_semester/research_project/related_work/calibrated-backprojection-network/trained_kbnet/custom/kbnet_model/depth_model-14280.pth
  depth_model_restore_path: ${paths.data_dir}/ckpts/benchmarking/kbnet-kitti.pth
  save_outputs: true
  output_path: ${paths.output_dir}/kbnet_results
  # output_path: /media/master/MyPassport/msc_studies/second_semester/research_project/related_work/calibrated-backprojection-network/results/kitti_dc_val
  keep_input_filenames: false
  max_evaluate_depth: 100.0
  min_evaluate_depth: 0.0
  normalized_image_range:
    - 0.0
    - 1.0
  outlier_removal_kernel_size: 7
  outlier_removal_threshold: 1.5
  w_color: 0.15
  w_structure: 0.95
  w_sparse_depth: 0.60
  w_smoothness: 0.04
  augmentation_probability: 1.0
  weight_decay_depth: 0.0
  weight_decay_pose: 0.0
  learning_rate: 5e-5

ckpt_path: ${.config.depth_model_restore_path}