ds_name: kitti
batch_size: 8

split: eigen

data_path: null
filenames_file: ../data/data_splits/kitti_dc_partitioned.json  # ensure generalization on new videos

input_height: 352
input_width: 1216

do_crop: true
do_random_rotate: false
degree: 2.5

line_op: null
line_filter: null

use_grayscale_img: false
do_load_lines: false

target_shape: [640, 192]

min_length: 25
use_min_length: false

use_lines_to_infill_gt: false
rescale_after_deeplsd: false