batch_size: 8

data_path: /mnt/wext/msc_studies/monodepth_project/data/kitti/kitti-depth
filenames_file: /mnt/wext/msc_studies/monodepth_project/data/data_splits/kitti_official_valid.txt
do_kb_crop: true
mode: train

input_height: 352
input_width: 1216
do_random_rotate: false
degree: 2.5