batch_size: 1

data_path: /mnt/wext/msc_studies/monodepth_project/data/kitti/kitti-depth
filenames_file: /mnt/wext/msc_studies/monodepth_project/data/data_splits/kitti_official_valid.txt
gt_path: /mnt/wext/cv_data/kitti-full/kitti-depth-completion/data_depth_annotated/val
do_kb_crop: true
mode: train

input_height: 352
input_width: 1216
do_random_rotate: false
degree: 2.5