ds_name: kitti
batch_size: 16

split: eigen
# split: null

data_path: /mnt/wext/msc_studies/monodepth_project/data/kitti/kitti-depth
filenames_file: ../data/data_splits/kitti_dc.json

input_height: 352
input_width: 1216

do_kb_crop: true
do_random_rotate: false
degree: 2.5

line_op: null
line_filter: null

use_grayscale_img: false