ds_name: nyu
batch_size: 16
split: eigen

data_path: /mnt/wext/msc_studies/monodepth_project/data/nyuv2-depth
filenames_file: ../data/data_splits/nyu.json

do_random_rotate: false
degree: 2.5

line_op: null
line_filter: null

use_grayscale_img: false
do_load_lines: false

do_crop: true