ds_name: nyu
batch_size: 16
split: eigen

data_path: null
filenames_file: ../data/data_splits/nyu.json

do_random_rotate: false
degree: 2.5

line_op: null
line_filter: null

use_grayscale_img: false
do_load_lines: false

do_crop: true
target_shape: [256, 256]
# target_shape: [224, 224]

min_length: 15
use_min_length: false